services:
  nuii:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: nuii_frontend_dev
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - redis
      - searxng
    networks:
      - nuii_network

  redis:
    image: redis:alpine
    container_name: nuii_frontend_redis
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - nuii_network

  searxng:
    image: searxng/searxng
    container_name: nuii_searxng
    ports:
      - '127.0.0.1:${SEARXNG_PORT:-8080}:8080'
    env_file: .env
    volumes:
      - ./searxng-limiter.toml:/etc/searxng/limiter.toml
      - ./searxng-settings.yml:/etc/searxng/settings.yml
      - searxng_data:/data
    networks:
      - nuii_network

volumes:
  redis_data:
  searxng_data:

networks:
  nuii_network:
    driver: bridge
